language: perl
os:
  - osx
  - linux

perl:
    - "5.18"
    - "5.16"
    - "5.14"

env:
    matrix:
        - CC="clang"
        - CC="gcc"

before_install:
    - sudo apt-get install libgsl0-dev swig2.0
    - cpanm PkgConfig

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'

