language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libgsl0-dev swig2.0
    - cpanm PkgConfig

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'

