language: perl
dist: trusty
#os:
#  - osx
#  - linux

perl:
# Only test two versions for now until things settle down
#    - "5.24"
#    - "5.22"
    - "5.20"
    - "5.18"
#    - "5.16"
#    - "5.14"

env:
    matrix:
        - LD_LIBRARY_PATH=/tmp/gsl-2.2.1/lib:$LD_LIBRARY_PATH PATH=/tmp/gsl-2.2.1:$PATH
        - LD_LIBRARY_PATH=/tmp/gsl-1.15/lib:$LD_LIBRARY_PATH  PATH=/tmp/gsl-1.15:$PATH

addons:
  apt:
    packages:
      # - libgsl0-dev # this is 1.16 on trusty
      - swig2.0

before_install:
    - cpanm -n PkgConfig
    - export ORIG_DIR=`pwd`
    - cd /tmp
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-1.15.tar.gz
    - tar zxpf gsl-1.15.tar.gz
    - cd gsl-1.15
    - ./configure --prefix /tmp/gsl1.15 > /dev/null
    - make -j2 > /dev/null
    - make install > /dev/null
    - cd ..
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.2.1.tar.gz
    - tar zxpf gsl-2.2.1.tar.gz
    - cd gsl-2.2.1
    - ./configure --prefix /tmp/gsl2.2.1 > /dev/null
    - make -j2 > /dev/null
    - make install > /dev/null
    - ls -la /tmp/gsl.2.2.1/lib
    - cd ..
    - git clone --depth=5 https://github.com/leto/math--gsl.git
    - cd math--gsl
    - export PATH=/tmp/gsl2.2.1/bin:$PATH
    - perl Build.PL && ./Build && ./Build dist # create a CPAN dist with latest GSL
    - ls -la /tmp/math--gsl/Math-GSL*.tar.gz
    # now we have /tmp/math--gsl/Math-GSL*.tar.gz to test with
    - cd $ORIG_DIR

# Add verbosity for debugging
install:
    - cpanm  -vv --installdeps --notest .

script:
    - cd /tmp/math--gsl
    - tar zxpf Math-GSL*
    - cd Math-GSL*
    - perl Build.PL
    - ./Build
    - ./Build test

