language: perl
dist: trusty
git:
    depth: 5

cache:
  - ccache
  - apt
  - directories:
    - /tmp/gsl-2.2.1
    - /tmp/gsl-2.0
    - /tmp/gsl-2.1
    - /tmp/gsl-1.15
    - /tmp/gsl-1.16

before_cache:
  - rm -f /tmp/gsl-*/config.log /tmp/gsl-*/libtool

perl:
    - "5.24"
    - "5.20-extras" # -Duseshrplib -Duseithreads
    - "5.16"
    - "5.10"
    - "5.8"

env:
    global:
        - CCACHE_CPP2=1
        - CC="ccache clang"
        - MAKE="make -j2 &> /dev/null"
        - MAKE_INSTALL="make -j2 install &> /dev/null"
    matrix:
        - LD_LIBRARY_PATH=/tmp/gsl-2.2.1/lib:$LD_LIBRARY_PATH PATH=/tmp/gsl-2.2.1/bin:$PATH
        - LD_LIBRARY_PATH=/tmp/gsl-2.0/lib:$LD_LIBRARY_PATH   PATH=/tmp/gsl-2.0/bin:$PATH
        - LD_LIBRARY_PATH=/tmp/gsl-2.1/lib:$LD_LIBRARY_PATH   PATH=/tmp/gsl-2.1/bin:$PATH
        - LD_LIBRARY_PATH=/tmp/gsl-1.15/lib:$LD_LIBRARY_PATH  PATH=/tmp/gsl-1.15/bin:$PATH
        - LD_LIBRARY_PATH=/tmp/gsl-1.16/lib:$LD_LIBRARY_PATH  PATH=/tmp/gsl-1.16/bin:$PATH

addons:
  apt:
    packages:
      # - libgsl0-dev # this is 1.16 on trusty
      - gdb
      - ccache
      - swig2.0

before_install:
    - cpanm -n PkgConfig
    - export ORIG_DIR=`pwd`
    - echo ORIG_DIR=$ORIG_DIR
    - cd /tmp
    - wget -q ftp://ftp.gnu.org/gnu/gsl/gsl-1.15.tar.gz
    - tar zxpf gsl-1.15.tar.gz
    - cd gsl-1.15
    - ./configure --prefix /tmp/gsl-1.15 > /dev/null
    - `$MAKE`
    - `$MAKE_INSTALL`
    - cd ..
    - wget -q ftp://ftp.gnu.org/gnu/gsl/gsl-1.16.tar.gz
    - tar zxpf gsl-1.16.tar.gz
    - cd gsl-1.16
    - ./configure --prefix /tmp/gsl-1.16 > /dev/null
    - `$MAKE`
    - `$MAKE_INSTALL`
    - cd ..
    - wget -q ftp://ftp.gnu.org/gnu/gsl/gsl-2.2.1.tar.gz
    - tar zxpf gsl-2.2.1.tar.gz
    - cd gsl-2.2.1
    - ./configure --prefix /tmp/gsl-2.2.1 > /dev/null
    - `$MAKE`
    - `$MAKE_INSTALL`
    - ls -la /tmp/gsl-2.2.1/lib
    - cd ..
    - wget -q ftp://ftp.gnu.org/gnu/gsl/gsl-2.0.tar.gz
    - tar zxpf gsl-2.0.tar.gz
    - cd gsl-2.0
    - ./configure --prefix /tmp/gsl-2.0 > /dev/null
    - `$MAKE`
    - `$MAKE_INSTALL`
    - ls -la /tmp/gsl-2.0/lib
    - cd ..
    - wget -q ftp://ftp.gnu.org/gnu/gsl/gsl-2.1.tar.gz
    - tar zxpf gsl-2.1.tar.gz
    - cd gsl-2.1
    - ./configure --prefix /tmp/gsl-2.1 > /dev/null
    - `$MAKE`
    - `$MAKE_INSTALL`
    - ls -la /tmp/gsl-2.1/lib
    - cd /home/travis/build/leto/math--gsl
    - PATH=/tmp/gsl-2.2.1/bin:$PATH perl Build.PL &>/dev/null && ./Build &>/dev/null && ./Build dist # create a CPAN dist with latest GSL
    - cp Math-GSL*.tar.gz /tmp
    - ls -la /tmp/Math-GSL*.tar.gz # now we have a CPAN dist to test on each version of GSL
    - cd $ORIG_DIR

# Add verbosity for debugging
install:
    # this should always point to the version we build the CPAN dist with
    - PATH=/tmp/gsl-2.2.1/bin:$PATH cpanm --installdeps --notest . &> /dev/null

before_script:
    - ulimit -c unlimited -S       # enable core dumps

script:
    - cd /tmp
    - tar zxpf Math-GSL*
    - cd Math-GSL*
    - perl Build.PL
    - ./Build
    # - ./Build test verbose=1
    # -j3 saves us 3 seconds but makes the output really annoying to read
    - prove -rblvs t/

after_failure:
    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" `which perl` -ex "thread apply all bt" -ex "info registers" -ex "set pagination 0" -batch; fi
