language: perl
#os:
#  - osx
#  - linux

perl:
    - "5.18"
    - "5.16"
    - "5.14"

env:
    matrix:
        - CC="clang"
        - CC="gcc"

addons:
  apt:
    packages:
      - libgsl0-dev
      - swig2.0

before_install:
    - cpanm -n PkgConfig

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'

