language: perl
dist: trusty
#os:
#  - osx
#  - linux

perl:
# Only test two versions for now until things settle down
#    - "5.24"
#    - "5.22"
    - "5.20"
    - "5.18"
#    - "5.16"
#    - "5.14"

env:
    matrix:
        - PATH=/tmp/gsl-2.2.1:$PATH
        - PATH=/tmp/gsl-1.15:$PATH


addons:
  apt:
    packages:
      # - libgsl0-dev # this is 1.16 on trusty
      - swig2.0

before_install:
    - cpanm -n PkgConfig
    - cd /tmp
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-1.15.tar.gz
    - tar zxpf gsl-1.15.tar.gz
    - cd gsl-1.15
    - ./configure --prefix /tmp/gsl1.15
    - make -j2
    - make install
    - cd ..
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.2.1.tar.gz
    - tar zxpf gsl-2.2.1.tar.gz
    - cd gsl-2.2.1
    - ./configure --prefix /tmp/gsl2.2.1
    - make -j2
    - make install
    - cd ..
    - git clone --depth=5 https://github.com/leto/math--gsl.git
    - cd math--gsl
    - export PATH=/tmp/gsl2.2.1/bin:$PATH
    - perl Build.PL && ./Build && ./Build dist # create a CPAN dist with latest GSL
    - ls -la /tmp/math--gsl/Math-GSL*.tar.gz
    # now we have /tmp/math--gsl/Math-GSL*.tar.gz to test with

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'

script:
    - cd /tmp/math--gsl && tar zxpf Math-GSL* && cd Math-GSL* && perl Build.PL && ./Build && ./Build test

