language: perl
#os:
#  - osx
#  - linux

perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

env:
    matrix:
        - CC="clang"
        - CC="gcc"

addons:
  apt:
    packages:
      - libgsl0-dev

before_install:
    - cpanm -n PkgConfig
    # swig 2.0.4 is not compatible with Perl 5.20 and up
    - wget https://github.com/swig/swig/archive/rel-2.0.12.tar.gz
    - tar zxpf rel-2.0.12.tar.gz
    - cd swig-rel-2*
    - ./autogen.sh
    - ./configure --disable-ccache
    - make -j2
    - sudo make install
    - cd ..

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'

