language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"

before_script:
    - sudo apt-get install libgsl0-dev

before_install:
    - cpanm ExtUtils::PkgConfig

install: 'cpanm  -vv --quiet --installdeps --notest .'
