language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"

before_install:
    - sudo apt-get install libgsl0-dev swig
    - cpanm ExtUtils::PkgConfig

# Add verbosity for debugging
install: 'cpanm  -vv --installdeps --notest .'
